# Generated by Django 5.1.7 on 2025-03-30 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_task_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('planning', 'Planning'), ('to_do', 'To Do'), ('in_progress', 'In Progress'), ('done', 'Done'), ('finished', 'Finished')], default='planning', max_length=20),
        ),
    ]
